.TH ASCII2MAP 1
.SH NAME
ascii2map, map2ascii \- map data conversion
.SH SYNOPSIS
.B ascii2map
[
.B -f
]
.I mapfile
.br
.B map2ascii 
.I "lat lon
[
.I mapfile
[
.I index
]]
.SH DESCRIPTION
.I Ascii2map
creates a
.IR map(5)
file named
.I mapfile,
and an associated index
.IB mapfile .x , 
from latitude-longitude data on standard input.
Resolution in
.I mapfile
is .0001 radian by default and .00001 radian under option
.BR -f .
.PP
The input data is a sequence of connected segements,
each of which is represented as a decimal count,
.I n,
followed by
.I n
decimal latitude-longitude pairs, where west longitude
is positive.
.PP
.I Map2ascii
converts all the segments in one 10-degree patch of the
.I mapfile
.RB (default /usr/dict/world )
into
.I ascii2map
input format.
.I Lat
and
.I lon
are multiples of 10, the minimum coordinates
of the patch.
If no 
.I index 
is specified,
.IB mapfile .x
is understood.
.SH "SEE ALSO
.IR map (5),
.IR map (1)

