all: map.1.ps map.3.ps map.5.ps route.1.ps ascii2map.1.ps

map.1.ps: map.1
	groff -man map.1 >map.1.ps

map.3.ps: map.3
	groff -man map.3 >map.3.ps

map.5.ps: map.5
	groff -man map.5 >map.5.ps

route.1.ps: route.1
	groff -man route.1 >route.1.ps

ascii2map.1.ps: ascii2map.1
	groff -man ascii2map.1 >ascii2map.1.ps
