.TH ROUTE 1
.SH NAME
route \- identify great circle between two points
.SH SYNOPSIS
.B route
[
.B -t
]
.SH DESCRIPTION
.I Route
repeatedly
reads two latitude-longitude pairs (white-space punctuation)
from standard input.  With no option,
it places on standard output
.B -o
options for
.IR map (1)
that will place the equator of the tilted, rotated
coordinate system along the great circle from point
A to point B (west to east) and from B to A.
With each option it also gives
the coordinates of the two
points in the new coordinate system, thus giving
the extent of a strip map of the great circle route
(useful for setting limits with the
.B -w
option to 
.IR map ).
.PP
Under option 
.B -t
.I route
produces a sequence of points along the great circle,
useful for a
.B -t 
track for 
.IR map .
.SH "SEE ALSO
.IR map (1)
.SH COPYRIGHT
.PP
Copyright (C) 1998, Lucent Technologies
.br
All rights reserved
